### ISSUE TITLE
name 'corr_sampler' is not defined

### ISSUE THREAD

**Issue by TouqeerAhmad** [facebookresearch/TemporallyConsistentDepth#3]
Hello, 

I was trying to run the code using MPI dataset and facing this error: "name 'corr_sampler' is not defined". It is triggering due to RAFT Stereo, also an open issue on RAFT repo: https://github.com/princeton-vl/RAFT-Stereo/issues/80

May be instructions for this repo need to be updated as how to run out of box without facing this error? As currently it is not running due to one of the dependency. 

Thanks!

**Comment by nkhan2** [comment]
Thanks for pointing this out. I'll push a fix soon. In the meantime, you can modify the options on line 34 of `raftstereo_wrapper.py` to run RAFT Stereo without the CUDA sampler.

**Comment by TouqeerAhmad** [comment]
Thank you, that worked -- looking forward to the fix.
