### ISSUE TITLE
MPI Sintel: Mono vs Stereo 

### ISSUE THREAD

**Issue by TouqeerAhmad** [facebookresearch/TemporallyConsistentDepth#4]
I was curious about running the TCOD on mono depth from MPI Sintel, as results for both mono/stereo are reported in the paper. More specifically, I was expecting to run the trained temporal/spatial fusion model providing the ground truth depth (or predicted depth via DPT), camera parameters, and RGB image from the monocular partition: http://sintel.is.tue.mpg.de/depth

I do not see any option in the code to run mono part of MPI Sintel? Would that fall under running with the custom dataset? 

Instead, mpisintel option runs RAFT Stereo to generate depth and then runs the proposed network. Specifically works on this dataset: http://sintel.is.tue.mpg.de/stereo

Is it safe to assume mono option is unavailable or is there a plan to add that?

**Comment by nkhan2** [comment]
Hi Touqeer. Yes, I would suggest implementing a custom dataset for running monocular tests on MPI Sintel. I believe you should be able to borrow large parts of the code from the monocular ScanNet dataloader and add the pose loading for MPI Sintel from the stereo loader.

**Comment by TouqeerAhmad** [comment]
Thanks, I shall give it a try.
