### ISSUE TITLE
Details for reproducing the tables.

### ISSUE THREAD

**Issue by kami93** [facebookresearch/TemporallyConsistentDepth#6]
Hi. Thanks for your efforts.

I am trying to reproduce the main table 1 reported in the paper, however, I am struggling to find which exact sample names and frame durations are used for your evaluation. The paper reports that: 
> We evaluate the monocular variant of our method on 20 60-frame sequences from different scenes.

Perhaps more details including the sample names and the frame duration could be shared? Thanks!

**Comment by nkhan2** [comment]
Hi kami93,
Thank you for your comment. We use the first 60 frames (0.jpg to 59.jpg) from the first 20 scenes of the ScanNet dataset (scene0000_00 to scene0019_00) for our evaluation.

**Comment by nkhan2** [comment]
I believe this issue has been resolved.
