### ISSUE TITLE
Camera poses of the stereo videos

### ISSUE THREAD

**Issue by yavon818** [facebookresearch/TemporallyConsistentDepth#7]
I've noticed that the left camera poses of the MPI dataset have been used in your paper, and I wonder if the poses of the right to left should be considered in your algorithm, or only single pose data is needed.

**Comment by nkhan2** [comment]
Hi,
In our stereo example using MPI-Sintel, we only estimate temporally consistent depth for one camera. We choose the left camera as the MPI-Sintel dataset directly provides the pose for the left camera. 

If you would like to estimate the depth for both left and right cameras then, yes, you would need the pose for the right camera as well (for MPI-Sintel you can compute this knowing that the baseline between the left and right camera is 10cm). You would have to call `pcupdater.update(...)` on line 71 of [run.py](https://github.com/facebookresearch/TemporallyConsistentDepth/blob/main/run.py) twice, once for each camera.

I hope this answers your question.
