### ISSUE TITLE
save fusion point3ds

### ISSUE THREAD

**Issue by cv-lab-x** [facebookresearch/TemporallyConsistentDepth#9]
hi, thanks for your great work, how to save the fusion point3ds of your work? @numairkhan2
Looking forward to your reply, thanks!

**Comment by nkhan2** [comment]
Hi. You can access the 3D points, their RGB color values and their confidence in [run.py](https://github.com/facebookresearch/TemporallyConsistentDepth/blob/main/run.py) after each video frame has been processed by adding the following on line 75 :
`pts_xyz = pcupdater.pc[0][:3, :]`
`pts_rgb = pcupdater.pc[0][4:, :]`
`pts_conf = pcupdater.pc_w[0]`
